version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t package/
  build:
    commands:
      - echo "Preparing ZIP file..."
      - cp *.py package/
      - cd package
      - zip -r ../deployment.zip .
      - cd ..
  post_build:
    commands:
      - echo "Deploying a AWS Lambda..."
      - aws lambda update-function-code --function-name upload-to-search --zip-file fileb://deployment.zip